apiVersion: v1
data:
  data-prepper-config: |
    ssl: false
  data-prepper-pipeline: |
    otel-logs-pipeline:
      workers: 5
      delay: 10
      source:
        otel_logs_source:
          ssl: false
      buffer:
        bounded_blocking:
      sink:
        - opensearch:
            hosts: [ "https://opensearch-cluster-leader.default.svc:9200" ]
            insecure: true
            username: $USERNAME
            password: $PASSWORD
            index_type: custom
            index: otel-events-%{yyyy.MM.dd}
            bulk_size: 4
    
    entry-pipeline:
      delay: "100"
      source:
        otel_trace_source:
          ssl: false
      sink:
        - pipeline:
            name: "raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"
    raw-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      processor:
        - otel_trace_raw:
      sink:
        - opensearch:
            hosts: [ "https://opensearch-cluster-leader.default.svc:9200" ]
            insecure: true
            username: $USERNAME
            password: $PASSWORD
            index_type: trace-analytics-raw
    service-map-pipeline:
      delay: "100"
      source:
        pipeline:
          name: "entry-pipeline"
      processor:
        - service_map_stateful:
      sink:
        - opensearch:
            hosts: [ "https://opensearch-cluster-leader.default.svc:9200" ]
            insecure: true
            username: $USERNAME
            password: $PASSWORD
            index_type: trace-analytics-service-map
    otel-metrics-pipeline:
      workers: 8
      delay: 3000
      source:
        otel_metrics_source:
          health_check_service: true
          ssl: false
      buffer:
        bounded_blocking:
          buffer_size: 1024 # max number of records the buffer accepts
          batch_size: 1024 # max number of records the buffer drains after each read
      processor:
        - otel_metrics:
            calculate_histogram_buckets: true
            calculate_exponential_histogram_buckets: true
            exponential_histogram_max_allowed_scale: 10
            flatten_attributes: false
      sink:
        - opensearch:
            hosts: [ "https://opensearch-cluster-leader.default.svc:9200" ]
            insecure: true
            username: $USERNAME
            password: $PASSWORD
            index_type: custom
            index: otel-metrics-%{yyyy.MM.dd}
            bulk_size: 4
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            cors:
              allowed_origins:
                - "http://*"
                - "https://*"
    exporters:
      debug:
      otlp:
        endpoint: "jaeger-service:4317"
        tls:
          insecure: true
      otlp/traces:
        endpoint: "data-prepper-service:21890"
        tls:
          insecure: true
          insecure_skip_verify: true
      otlp/data-prepper:
        endpoint: "data-prepper-service:21891"
        tls:
          insecure: true
          insecure_skip_verify: true
      otlp/logs:
        endpoint: "data-prepper-service:21892"
        tls:
          insecure: true
          insecure_skip_verify: true
      otlphttp/prometheus:
        endpoint: "http://prometheus-service:9090/api/v1/otlp"
        tls:
          insecure: true
    processors:
      batch:
      filter/ottl:
        error_mode: ignore
        metrics:
          metric:
            - 'name == "rpc.server.duration"'
      transform:
        metric_statements:
          - context: metric
            statements:
              - set(description, "") where name == "queueSize"
              - set(description, "") where name == "http.client.duration"
    connectors:
      spanmetrics:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, debug, spanmetrics, otlp/traces]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [filter/ottl, transform, batch]
          exporters: [otlphttp/prometheus, otlp/data-prepper, debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/logs, debug]
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-21T19:54:36Z"
  name: otel-configmap
  namespace: default
  resourceVersion: "123972540"
