apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-data-refresh-cronjob
spec:
  # Runs everyday at 1 am UTC
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sample-data-refresh-cronjob
              image: public.ecr.aws/j6b3p0p7/sample-data-tooling:latest
              env:
              - name: SAMPLE_DATA_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: sample-data-secret
                    key: username
              - name: SAMPLE_DATA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: sample-data-secret
                    key: password
                # SAMPLE_DATA_HOST is a host name or IP without the scheme
                # ex: SAMPLE_DATA_HOST=localhost
              - name: SAMPLE_DATA_HOST
                valueFrom:
                  secretKeyRef:
                    name: sample-data-secret
                    key: host
              command: ["python3"]
              args: ["./sample_data_jobs/refresh_job.py"]
          restartPolicy: OnFailure