name: Dev - Deploy OS and OSD

on:
    push:
        branches:
            - actionandhelm

jobs:
  # The first job in this workflow, it is praparing the ubuntu
  OS-OSD-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Setp 2 - Deploy OpenSearch and OpenSearch Dashboards By Helm Chart
        uses: elastic-analytics/dashboards-action@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_DEV }}
        with:
          plugins: "" # optional
          command: |
            pwd
            kubectl get nodes
            helm repo add opensearch https://opensearch-project.github.io/helm-charts/
            helm repo update
            helm search repo opensearch
            helm install opensearch opensearch/opensearch -f /home/runner/work/dashboards-anywhere/dashboards-anywhere/config/playground/helm/helm-os.yaml
            helm install dashboards opensearch/opensearch-dashboards -f /home/runner/work/dashboards-anywhere/dashboards-anywhere/config/playground/helm/helm-osd.yaml
