name: OpenSearch Dashboards Function Tests Template

on:
  workflow_call:
    inputs:
      endpoint:
        required: true
        type: string
    secrets:
      osd-user:
        required: true
      osd-user-password:
        required: true

env:
  # TODO: merge all the changes to OpenSearch-Project's function repo.
  function-repo: elastic-analytics/opensearch-dashboards-functional-test
  function-branch: playground

jobs:

  # Run OpenSearch Dashboard tests first and then
  # run all the plugin tests in parallel.
  OSD-Functional-Test-OSD:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout function test repo
          uses: actions/checkout@v3
          with:
            repository: $function-repo
            ref: $function-branch

        - name: Step 0 - Install dependencies for function test
          run: |
            npm install
            npm install -g yarn

        - name: Step 1 - Check If OSD is Up
          run: |
            sleep 30s
            curl -XGET -k -u '${{secrets.osd-user}}:${{secrets.osd-user-password}}' '${{inputs.endpoint}}/api/status' > $HOME/osd-response.json
            echo "OSD_STATUS=$(cat $HOME/osd-response.json | jq -r '.status.overall.state')" >> $GITHUB_ENV

        - name: Step 2 - Run Function Test For OSD
          if: ${{ env.OSD_STATUS == 'green'}}
          run: |
            yarn cypress run --spec "cypress/integration/playground/dashboards/*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

  OSD-Functional-Test-AD:
      needs: [OSD-Functional-Test-OSD]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout function test repo
          uses: actions/checkout@v3
          with:
            repository: $function-repo
            ref: $function-branch

        - name: Step 0 - Install dependencies for function test
          run: |
            npm install
            npm install -g yarn

        - name: Step 1 - Run Function Test For AD
          run: |
            yarn cypress run --spec "cypress/integration/playground/plugins/playground_ad*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

  OSD-Functional-Test-Alert:
      needs: [OSD-Functional-Test-OSD]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout function test repo
          uses: actions/checkout@v3
          with:
            repository: $function-repo
            ref: $function-branch

        - name: Step 0 - Install dependencies for function test
          run: |
            npm install
            npm install -g yarn

        - name: Step 1 - Run Function Test For Alert
          run: |
            yarn cypress run --spec "cypress/integration/playground/plugins/playground_alert*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

  OSD-Functional-Test-Notifications:
      needs: [OSD-Functional-Test-OSD]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout function test repo
          uses: actions/checkout@v3
          with:
            repository: $function-repo
            ref: $function-branch

        - name: Step 0 - Install dependencies for function test
          run: |
            npm install
            npm install -g yarn

        - name: Step 1 - Run Function Test For Alert
          run: |
            yarn cypress run --spec "cypress/integration/playground/plugins/playground_notifications*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

  OSD-Functional-Test-Reports:
      needs: [OSD-Functional-Test-OSD]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout function test repo
          uses: actions/checkout@v3
          with:
            repository: $function-repo
            ref: $function-branch

        - name: Step 0 - Install dependencies for function test
          run: |
            npm install
            npm install -g yarn

        - name: Step 1 - Run Function Test For Reports
          run: |
            yarn cypress run --spec "cypress/integration/playground/plugins/playground_reports*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

  OSD-Functional-Test-Observability:
      needs: [OSD-Functional-Test-OSD]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout function test repo
          uses: actions/checkout@v3
          with:
            repository: $function-repo
            ref: $function-branch

        - name: Step 0 - Install dependencies for function test
          run: |
            npm install
            npm install -g yarn

        - name: Step 1 - Run Function Test For Observability
          run: |
            yarn cypress run --spec "cypress/integration/playground/plugins/playground_observability*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"


  OSD-Functional-Test-IndexMan:
      needs: [OSD-Functional-Test-OSD]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout function test repo
          uses: actions/checkout@v3
          with:
            repository: $function-repo
            ref: $function-branch

        - name: Step 0 - Install dependencies for function test
          run: |
            npm install
            npm install -g yarn

        - name: Step 1 - Run Function Test For Index Management
          run: |
            yarn cypress run --spec "cypress/integration/playground/plugins/playground_index*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"